name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_IMAGE_BASE_NAME: murilocardoso/tsidgeneratorbackend
  RENDER_SERVICE_ID: srv-cr6hhnjqf0us73ef55c0
  RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checar o código
      uses: actions/checkout@v3

    - name: Configurar JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Construir com Maven
      run: mvn clean verify

    - name: Construir imagem Docker
      run: |
        docker build -t ${{ env.DOCKER_IMAGE_BASE_NAME }}:${{ github.sha }} .

    - name: Login no Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push da imagem Docker
      run: docker push ${{ env.DOCKER_IMAGE_BASE_NAME }}:${{ github.sha }}

    - name: Acionar deploy no Render
      run: |
        curl -X POST "https://api.render.com/v1/services/${{ env.RENDER_SERVICE_ID }}/deploys" \
        -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
        -H "Content-Type: application/json" \
        -d '{"imageUrl": "${{ env.DOCKER_IMAGE_BASE_NAME }}:${{ github.sha }}"}'
