name: Development Pipeline

on:
  push:
    branches-ignore:
      - main # Executa em qualquer branch que não seja a main
  pull_request:
    branches-ignore:
      - main # Executa para qualquer pull request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checar o código
      uses: actions/checkout@v3

    - name: Configurar JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Construir e testar com Maven
      run: mvn clean verify
